---

# #
# # Clean out and clone repo
# #
# - name: Clone CATPOO repo
#   git:
#     accept_hostkey: yes
#     clone: yes
#     dest: "{{ ansible_env.HOME }}/src/catpoo"
#     force: yes
#     recursive: yes
#     repo: "git@github.com:timmd909/catpoo.git"
#     version: master
#
# #
# # Install dependencies
# #
# - name: Install Composer vendors
#   shell: "composer --no-interaction install"
#   args:
#     chdir: "{{ ansible_env.HOME }}/src/catpoo/www"
# - name: Install Node modules
#   shell: npm install
#   args:
#     chdir: "{{ ansible_env.HOME }}/src/catpoo"
#
# #
# # Configure web server
# #
# - name: Update www-data ACL for CATPOO
#   acl:
#     default: yes
#     entity: "{{ apache_username }}"
#     etype: user
#     name: "{{ item }}"
#     permissions: "rwx"
#     recursive: yes
#     state: present
#   with_items:
#     - "{{ ansible_env.HOME }}/src/catpoo/www/app/cache"
#     - "{{ ansible_env.HOME }}/src/catpoo/www/app/logs"
#
# - name: Update user ACL for CATPOO
#   acl:
#     default: yes
#     entity: "{{ ansible_env.USER }}"
#     etype: user
#     name: "{{ item }}"
#     permissions: "rwx"
#     recursive: yes
#     state: present
#   with_items:
#     - "{{ ansible_env.HOME }}/src/catpoo/www/app/cache"
#     - "{{ ansible_env.HOME }}/src/catpoo/www/app/logs"
#
# - name: Install Apache CATPOO site configuration
#   template:
#     dest: "{{ ansible_env.HOME }}/src/catpoo/config/catpoo-site"
#     src: "home/user/src/catpoo/config/catpoo-site.j2"
#
# - name: Symlink CATPOO site configuration
#   become: yes
#   become_user: root
#   file:
#     state: link
#     src: "{{ ansible_env.HOME }}/src/catpoo/config/catpoo-site"
#     path: /etc/apache2/sites-available/catpoo-site.conf
#
# - name: Enable Apache modules for CATPOO
#   become: yes
#   become_user: root
#   apache2_module: state=present name="{{ item }}"
#   with_items:
#     - proxy
#     - proxy_http
#
# - name: Enable CATPOO site
#   become: yes
#   become_user: root
#   shell: a2ensite catpoo-site
#
# - name: Restart Apache
#   become: yes
#   become_user: root
#   shell: service apache2 restart
#
