---

#
# Install Composer
#
- name: Download Composer
  shell: "{{ item }}"
  with_items:
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php

- name: Install Composer
  shell: "cp composer.phar /usr/local/bin/composer"
  sudo: yes

- name: Cleanup Composer
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_env.HOME }}/composer-setup.php"
    - "{{ ansible_env.HOME }}composer.phar"

#
# Clean out and clone repo
#
- name: Clone CATPOO repo
  git:
    accept_hostkey: yes
    clone: yes
    dest: "{{ ansible_env.HOME }}/src/catpoo"
    force: yes
    recursive: yes
    repo: "git@github.com:timmd909/catpoo.git"
    version: master

#
# Install dependencies
#
- name: Install Composer vendors
  shell: "composer --no-interaction install"
  args:
    chdir: "{{ ansible_env.HOME }}/src/catpoo/www"
- name: Install Node modules
  shell: npm install
  args:
    chdir: "{{ ansible_env.HOME }}/src/catpoo"

#
# Configure web server
#
- name: Update www-data ACL for CATPOO
  acl:
    default: yes
    entity: "{{ apache_username }}"
    etype: user
    name: "{{ item }}"
    permissions: "rwx"
    recursive: yes
    state: present
  with_items:
    - "{{ ansible_env.HOME }}/src/catpoo/www/app/cache"
    - "{{ ansible_env.HOME }}/src/catpoo/www/app/logs"

- name: Update user ACL for CATPOO
  acl:
    default: yes
    entity: "{{ ansible_env.USER }}"
    etype: user
    name: "{{ item }}"
    permissions: "rwx"
    recursive: yes
    state: present
  with_items:
    - "{{ ansible_env.HOME }}/src/catpoo/www/app/cache"
    - "{{ ansible_env.HOME }}/src/catpoo/www/app/logs"

- name: Install Apache CATPOO site configuration
  template:
    dest: "{{ ansible_env.HOME }}/src/catpoo/config/catpoo-site"
    src: "home/user/src/catpoo/config/catpoo-site.j2"

- name: Symlink CATPOO site configuration
  sudo: yes
  file:
    state: link
    src: "{{ ansible_env.HOME }}/src/catpoo/config/catpoo-site"
    path: /etc/apache2/sites-available/catpoo-site.conf

- name: Enable Apache modules for CATPOO
  sudo: yes
  apache2_module: state=present name="{{ item }}"
  with_items:
    - proxy
    - proxy_http

- name: Enable CATPOO site
  sudo: yes
  shell: a2ensite catpoo-site

- name: Restart Apache
  sudo: yes
  shell: service apache2 restart

#
# Build any 3rd party libraries necessary
#
- name: Prepare Thrift for compilation
  shell: "{{ item }}"
  args:
    chdir: "{{ ansible_env.HOME }}/src/catpoo/3rdparty/thrift"
    creates: "{{ ansible_env.HOME }}/src/catpoo/3rdparty/thrift/Makefile"
  with_items:
    - ./bootstrap.sh
    - ./configure --without-qt4 --without-csharp --without-java --without-erlang --without-perl --without-haskell --without-go --without-d --with-cpp

- name: Compile Thrift
  shell: make
  args:
    chdir: "{{ ansible_env.HOME }}/src/catpoo/3rdparty/thrift"

- name: Install Thrift
  shell: make install
  sudo: yes
  args: chdir="{{ ansible_env.HOME }}/src/catpoo/3rdparty/thrift"
