---

#
# CATPOO controller
#

- name: Clone CATPOO controller repo
  git:
    accept_hostkey: yes
    clone: yes
    dest: /usr/local/src/catpoo-controller
    force: yes
    recursive: yes
    repo: "{{ catpoo_controller_repo }}"
    version: master

- name: Build CATPOO controller
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/catpoo-controller
  with_items:
    - autoreconf --install
    - ./configure
    - make

#
# CATPOO web UI
#

- name: Clone CATPOO Web UI repo
  git:
    accept_hostkey: yes
    clone: yes
    dest: "{{ catpoo_document_root }}"
    force: yes
    recursive: yes
    repo: "{{ catpoo_web_repo }}"
    version: master

#
# Apache configuration
#
- name: Configure web server
  template:
    src: etc/apache2/sites-available/catpoo.conf.j2
    dest: /etc/apache2/sites-available/catpoo.conf

- name: Enable catpoo Apache config
  shell: "a2ensite catpoo"
  notify: "Restart Apache"
  when: catpoo_web_ui == true

- name: Disable catpoo Apache config
  shell: "a2dissite catpoo"
  notify: "Restart Apache"
  when: catpoo_web_ui == false

- name: Enable Apache modules for CATPOO
  apache2_module: state=present name="{{ item }}"
  with_items:
    - proxy
    - proxy_http

- name: Fix ownership & permissions in CATPOO webroot
  file:
    owner: www-data
    group: www-data
    path: "{{ catpoo_document_root }}"
    recurse: yes

#
# Update CATPOO webroot ACLs
#
- name: Update www-data ACL for CATPOO defaults
  acl:
    default: yes
    entity: "{{ apache_username }}"
    etype: user
    path: "{{ catpoo_document_root }}"
    permissions: "rwx"
    recursive: yes
    state: present

- name: Update www-data ACL for CATPOO
  acl:
    entity: "{{ apache_username }}"
    etype: user
    path: "{{ catpoo_document_root }}"
    permissions: "rwx"
    recursive: yes
    state: present

- name: Update user ACL for CATPOO defaults
  acl:
    default: yes
    entity: "{{ ansible_env.USER }}"
    etype: user
    path: "{{ catpoo_document_root }}"
    permissions: "rwx"
    recursive: yes
    state: present

- name: Update user ACL for CATPOO
  acl:
    entity: "{{ ansible_env.USER }}"
    etype: user
    path: "{{ catpoo_document_root }}"
    permissions: "rwx"
    recursive: yes
    state: present

# #
# # Install dependencies
# #
# - name: Install Composer vendors
#   shell: "composer --no-interaction install"
#   args:
#     chdir: "{{ ansible_env.HOME }}/src/catpoo/www"
# - name: Install Node modules
#   shell: npm install
#   args:
#     chdir: "{{ ansible_env.HOME }}/src/catpoo"
#
# #
# # Configure web server
# #
# - name: Restart Apache
#   become: yes
#   become_user: root
#   shell: service apache2 restart
