---

- debug: var=ansible_env

- name: Create CATPOO srv directory
  file:
    state: directory
    path: "{{ catpoo_root }}"
    owner: "{{ ansible_env.USER }}"
    # group: "{{ ansible_env.GROUP }}"

#
# CATPOO drive
#

- name: Clone CATPOO drive repo
  git:
    accept_hostkey: yes
    clone: yes
    dest: "{{ catpoo_drive_root }}"
    force: yes
    recursive: yes
    repo: "{{ catpoo_drive_repo }}"
    version: "{{ catpoo_drive_repo_version }}"
  become: yes
  become_user: "{{ ansible_env.USER }}"

#
# CATPOO web UI
#

- name: Clone CATPOO Web UI repo
  git:
    accept_hostkey: yes
    clone: yes
    dest: "{{ catpoo_web_root }}"
    force: yes
    recursive: yes
    repo: "{{ catpoo_web_repo }}"
    version: "{{ catpoo_web_repo_version }}"
  become: yes
  become_user: "{{ ansible_env.USER }}"

#
# Apache configuration
#
- name: Enable Apache modules for CATPOO
  apache2_module: state=present name="{{ item }}"
  with_items:
    - proxy
    - proxy_http

- name: Configure web server
  template:
    src: etc/apache2/sites-available/catpoo.conf.j2
    dest: /etc/apache2/sites-available/catpoo.conf

- name: Enable catpoo Apache config
  shell: "a2ensite catpoo"
  notify: "Restart Apache"

# #
# # Update permissions
# #
# - name: Add www-data user to I2C group
#   user:
#     name: www-data
#     append: yes
#     groups: i2c
#
