#
# Programming languages
#
- name: Install build utilities
  apt: name="{{ item }}"
  with_items:
    - autoconf
    - automake
    - build-essential
    - byacc
    - cmake
    - flex
    - libtool
    - m4
    - make

- name: Install GCC, G++
  apt: name="{{ item }}"
  with_items:
    - gpp
    - gcc
    - g++

- name: Install Python
  apt: name="{{ item }}"
  with_items:
    - python
    - python-pysqlite2
    - python-smbus

- name: Install Node and NPM
  apt: name="{{ item }}"
  with_items:
    - nodejs
    - npm

- name: Install Grunt CLI
  shell: npm install -g grunt-cli

- name: "Install miscellaneous libraries"
  apt: name="{{ item }}"
  with_items:
    - libboost-all-dev
    - libcgicc-dev
    - libcgicc3
    - libsdl2-ttf-dev
    - libsdl2-dev
    - libx11-dev
    - libxext-dev
    - libxi-dev
    - x11proto-input-dev
