---

- include: "hardware.yml"
  sudo: yes
- include: "development.yml"
  sudo: yes
- include: "gui.yml"
  sudo: yes
- include: "opencv.yml"
  sudo: yes
- include: "miscellaneous.yml"
  sudo: yes
- include: "network.yml"
  sudo: yes

- include: "user-env.yml"
  sudo: no
- include: "catpoo.yml"
  sudo: no
