---

- name: 'Disable saving pictures'
  lineinfile:
    line: 'output_pictures off'
    path: /etc/motion/motion.conf
    regexp: '^output_pictures'
    state: present

- name: 'Disable saving videos'
  lineinfile:
    line: 'ffmpeg_output_movies off'
    path: /etc/motion/motion.conf
    regexp: '^ffmpeg_output_movies'
    state: present
